# Generated by Django 6.0.7 on 2026-07-27 23:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(choices=[('ByN', 'Blanco y Negro'), ('Color', 'Color')], default='ByN', max_length=10)),
                ('anillado', models.BooleanField(default=False)),
                ('caras', models.CharField(choices=[('Simple', 'Simple'), ('Doble', 'Doble')], default='Simple', max_length=10)),
                ('distribucion', models.CharField(choices=[('Normal', 'Normal'), ('Apaisada', 'Apaisada')], default='Normal', max_length=10)),
                ('seña', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('En proceso', 'En proceso'), ('Terminado', 'Terminado'), ('Cliente Avisado', 'Cliente Avisado'), ('Entregado', 'Entregado')], default='Nuevo', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['orden', '-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='adjuntos/%Y/%m/')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='pedidos.pedido')),
            ],
        ),
    ]
